version: "3.7"

services:
  redis1:
    image: redis:5.0.6-alpine
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.22.1.10
    ports:
      - "6379:6379"
    volumes:
      - ./redis1.conf:/usr/local/etc/redis/redis.conf

  redis2:
    image: redis:5.0.6-alpine
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.22.1.20
    ports:
      - "6380:6379"
    volumes:
      - ./redis2.conf:/usr/local/etc/redis/redis.conf
    depends_on:
      - redis1

networks:
  redis-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
