version: "3.7"

services:
  redis-0:
    image: redis:5.0.6-alpine
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./config-0
        target: /usr/local/etc/redis/

  redis-1:
    image: redis:5.0.6-alpine
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-network
    ports:
      - "6380:6379"
    volumes:
      - type: bind
        source: ./config-1
        target: /usr/local/etc/redis/

networks:
  redis-network:
